<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the 
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = array(
	'header' => array (
		'no' => 'Login med YubiKey',
		'nn' => 'Logg inn med YubiKey',
		'da' => 'Login med YubiKey',
		'en' => 'Login with YubiKey',
		'de' => 'Anmelden mit YubiKey',
		'sv' => 'Logga in med YubiKey',
		'fi' => 'Kirjaudu Yubikeylla',
		'es' => 'Accede utilizando YubiKey',
		'nl' => 'Inloggen met YubiKey',
		'sl' => 'Prijavi se z YubiKey',
		'hr' => 'Autenticirajte se pomoću YubiKey-a',
		'hu' => 'YubiKey bejelentkezés',
		'pl' => 'Login z YubiKey',
		'pt' => 'Entrar com YubiKey',
		'tr' => 'YubiKey ile giriş',
	),
	'intro' => array (
		'no' => 'En tjeneste har bedt om at du autentiserer deg. For å autentisere seg, trykk på knappen på din YubiKey. Feltet under vil da bli automatisk utfylt med et sikkert engangspassord.',
		'nn' => 'Ei webteneste har spurt om at du loggar inn.  For å logga inn, klikk på knappen på din YubiKey.  Feltet nedanfor blir automatisk fylt ut med eit sikkert eingongspassord når du trykker på YubiKey.',
		'da' => 'Nogle services kræver autentificering. For at autentificere klik på knappen på din YubiKey. Feltet herunder skulle nu automatisk blive udfyldt med et sikkert one-time-password.',
		'en' => 'Some service requested authentication. To authenticate, click the button on your YubiKey. The field below should then automatically be filled out with a secure one-time-password.',
		'de' => 'Ein Service verlangt nach Ihrer validierung. Bitte drücken Sie den Knopf auf Ihrem YubiKey. Ihr sicheres Einmalpasswort wird dann in das vorgesehene Feld geschrieben.',
		'sv' => 'En tjänst vill att du ska logga in. För att logga in tryck på knappen på din YubiKey. Fältet nedan ska när du trycker bli ifyllt med ett säkert engångslösenord.',
		'fi' => 'Jotkin palvelut vaativat käyttäjätunnistuksen. Paina nappia Yubikeyssasi tunnistautuaksesi. Allaolevaan kenttää tulee automaattisesti kertakäyttösalasanasi.',
		'es' => 'Un servicio ha solicitado que se autentique. Para autenticarse, haga clic en el botón de su YubiKey. El campo situado debajo debería rellenarse automática con una clave de un único uso (OTP) segura',
		'nl' => 'Een dienst vroeg om authenticatie. Om te authenticaren, klik op de knop van je YubiKey. In het veld hieronder zal dan automatisch een veilig eenmalig wachtwoord worden ingevuld.',
		'sl' => 'Nekatere storitve zahtevajo avtentikacijo, ki jo izvedete s klikom na gumb YubiKey. V polju spodaj se bo nato samodejno prikazalo geslo za enkratno uporabo.',
		'hr' => 'Aplikacija zahtjeva autentikaciju. Za autentikaciju kliknite gumb na vašem YubiKey-u. Nakon toga bi u polje ispod trebala biti automatski upisana jednokratna zaporka.',
		'hu' => 'Egy szolgáltatás azonosítást kért. Kérjük, nyomja meg a gombot a YubiKey-n! Az alábbi mező automatikusan ki kell, hogy töltődjön egy biztonságos egyszerhasználatos jelszóval.',
		'pl' => 'Jakiś serwis zażądał uwierzytelnienia. W celu uwierzytelnienia naciśnij przycisk na Twoim YubiKey. Następnie poniższe pole powinno zostać automatycznie wypełnione bezpiecznym jednorazowym hasłem.',
		'pt' => 'Um serviço necessita de autenticação. Para se autenticar, clique no botão da sua YubiKey. O campo em baixo deverá ser automaticamente preenchido com uma palavra-passe segura que funcionará apenas uma vez.',
		'tr' => 'Bazı servisler kimlik doğrulama istedi. Kimlik doğrulamak için, YubiKey\'iniz üzerindeki düğmeyi tıklayınız. Ondan sonra, güvenli bir tek kullanımlık şifre aşağıdaki alanda otomatik olarak belirecektir.',
	),

);


?>