<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the 
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = array(
	'header' => array (
		'no' => 'Tilbaketrekning av samtykke',
		'da' => 'Samtykke tilbagekaldelse',
		'en' => 'Consent withdrawal',
		'de' => 'Rückzug der Genehmigung',
		'sv' => 'Återtagande av samtycke',
		'es' => 'Retirar consentimiento',
		'nl' => 'Toestemming intrekken',
		'sl' => 'Preklic privolitve',
		'hu' => 'Hozzájárulás visszavonása',
		'pt' => 'Remover Consentimento',
		'tr' => 'Onaydan vazgeçme',
	),
	'granted' => array (
		'no' => 'Du har tidligere gitt samtykke %NO% ganger til %OF% forskjellige tjenester.',
		'da' => 'Du har tidligere givet %NO% samtykker til %OF% forskellige services.',
		'en' => 'You have earlier granted %NO% consents to %OF% different services.',
		'de' => 'Sie haben bisher %NO% Genehmigungen an %OF% verschiedene Services erteilt.',
		'sv' => 'Du har tidigare godkänt %NO% samtycken till %OF% olika tjänster.',
		'es' => 'Anteriormente permitió %NO% consentimientos para %OF% servicios diferentes.',
		'nl' => 'Je hebt eerder %NO% toestemmingen gegeven aan %OF% verschillende diensten.',
		'sl' => 'Potrdili ste %NO% privolitev za %OF% različnih storitev.',
		'hu' => '%NO% db. hozzájárulást adott %OF% különböző szolgáltatásnak.',
		'pt' => 'Você tem %NO% consentimentos definidos anteriormente para %OF% serviços diferentes.',
		'tr' => 'Daha önce %NO% onaylarını %OF% farklı servisler için garanti ettiniz.',
	),
	'info' => array (
		'no' => 'Dersom du trekker tilbake alle tidligere gitte samtykker, så vil du hver gang du besøker en tjeneste på nytt bli spurt om du aksepterer at en gitt liste med personlig informasjon blir overført til tjenesten.',
		'da' => 'Hvis du tilbagekalder alle dine samtykker, så vil du blive spurgt om at afgive samtykke hver gang du tilgår en ny tjeneste.',
		'en' => 'If you withdraw all consents given, you will be asked again each time you visit a new service, whether or not you would like to accept that a given set of personal information are transferred.',
		'de' => 'Wenn Sie alle Genehmigungen zurückziehen, müssen Sie beim erneuten Besuch eines Services, wieder die Genehmigung erteilen, dass Ihre personenbezogenen Daten übertragen werden dürfen.',
		'sv' => 'Om du drar tillbaka alla samtycken som du godkänt kommer du åter bli tillfrågad när du besöker tjänsterna för första gången oberoende om du vill eller inte vill godkänna att personuppgifter överförs.',
		'es' => 'Si retira todos los consentimientos concedidos, se le preguntará de nuevo cada vez que visite un nuevo servicio, independientemente de que acepte o rechace que un conjunto de datos personales sean transferidos.',
		'nl' => 'Als je alle gegeven toestemmingen intrekt, zal je elke keer dat je een nieuwe dienst bezoekt opnieuw gevraagd worden of je een gegeven set persoonsgegevens wilt vrijgeven.',
		'sl' => 'V primeru preklica vseh privolitev, boste ob dostopu do storitev ponovno pozvani k privolitvi posredovanja osebnih podatkov storitvi.',
		'hu' => 'Ha visszavonja az összes hozzájárulást, akkor minden alkalommal, amikor egy új szolgáltatást kíván igénybe venni, hozzá kell járulnia személyes adatainak kiadásához.',
		'pt' => 'Se remover os consentimentos definidos, ir-lhe-á ser perguntado se aceita o envio de informação pessoal de cada vez que aceder a um novo serviço.',
		'tr' => 'Verilen tüm onaylamalardan vazgeçerseniz, verilen bir kişisel bilgi kümesinin aktarılmasını kabul etmeyi isteseniz istemeseniz de, yeni bir servise her girdiğinizde tekrar sorgulanacaksınız',
	),
	'withdraw' => array (
		'no' => 'Trekk tilbake alle tidligere gitte samtykker',
		'da' => 'Tilbagekald alle samtykker',
		'en' => 'Withdraw all consent given',
		'de' => 'Alle Genehmigungen zurückziehen',
		'sv' => 'Dra tillbaka alla godkända samtycken',
		'es' => 'Retirar todos los consentimientos concedidos',
		'nl' => 'Trek alle gegeven toestemming in',
		'sl' => 'Prekliči vse privolitve.',
		'hu' => 'Az összes hozzájárulás visszavonása',
		'pt' => 'Remover todos os Consentimentos definidos',
		'tr' => 'Verilen tüm onaylardan vazgeç',
	),
	'headerstats' => array (
		'no' => 'Samtykke statistikk',
		'da' => 'Samtykkelager statestik',
		'en' => 'Consent Storage Statistics',
		'de' => 'Statistik über Ihre Genehmigungen',
		'sv' => 'Statistik för lagret över samtycken',
		'es' => 'Estadísticas de consentimientos almacenados',
		'nl' => 'Statistiek',
		'sl' => 'Statistika privolitev',
		'hu' => 'Hozzájárulás tároló statisztikák',
		'pt' => 'Estatísticas do armazenamento de Consentimentos',
		'tr' => 'Onay Depolama İstatistikleri',
	),
	'stattotal' => array (
		'no' => 'Samtykkelageret inneholder %NO% innslag.',
		'da' => 'Samtykkelager indeholder %NO% samtykker.',
		'en' => 'Consent storage contains %NO% entries.',
		'de' => 'Sie haben %NO% Genehmigungen erteilt',
		'sv' => 'Lagret innehåller %NO% samtycken.',
		'es' => 'El almacén de consentimientos tiene %NO% entradas.',
		'nl' => 'Je toestemmingsopslag bevat %NO% items.',
		'sl' => 'Privolitvena stran vsebuje %NO% zapisov.',
		'hu' => 'A hozzájárulás tároló %NO% bejegyzést tartalmaz.',
		'pt' => 'O armazenamento de consentimentos contém %NO% entradas.',
		'tr' => 'Onay depolama %NO% elemanları içermektedir',
	),
	'statusers' => array (
		'no' => '%NO% unike brukere har avgitt samtykke.',
		'da' => '%NO% unikke brugere har givet samtykke',
		'en' => '%NO% unique users have given consent.',
		'de' => '%NO% verschiedene Benutzer haben ihre Genehmigung erteilt',
		'sv' => '%NO% unika användare har lämnat samtycken.',
		'es' => '%NO% usuarios han dado su consentimiento.',
		'nl' => '%NO% unieke gebruikers hebben toestemming verleend.',
		'sl' => 'Privolitev je dalo %NO% različnih uporabnikov.',
		'hu' => '%NO% különböző felhasználó adott hozzájárulást.',
		'pt' => '%NO" utilizador distintos deram o seu consentimento.',
		'tr' => '%NO% biricik (unique) kullanıcılar onay verdi.',
	),
	'statservices' => array (
		'no' => 'Samtykke er avgitt til %NO% unike tjenester.',
		'da' => 'Samtykke er givet til %NO% unikke services.',
		'en' => 'Consent is given to %NO% unique services.',
		'de' => 'Genehmigung an %NO% Dienste erteilt',
		'sv' => 'Samtycken är lämnade för %NO% unika tjänster.',
		'es' => 'Consentimiento dado a %NO% servicios diferentes.',
		'nl' => 'Toestemming is verleend aan %NO% unieke diensten.',
		'sl' => '%NO% različnih storitev je dobilo privolitev.',
		'hu' => '%NO% különböző szolgáltatáshoz adtak hozzájárulást.',
		'pt' => 'Estão definidos consentimentos para %NO% serviços distintos.',
		'tr' => 'Onay %NO% biricik (unique) servislere veriliyor.',
	),

);


?>