cron-croninfo:
    path:       /info
    defaults:   { _controller: 'SimpleSAML\Module\cron\Controller\CronController::info' }
cron-run:
    path:       /run/{tag}/{key}/{output}
    defaults:   { _controller: 'SimpleSAML\Module\cron\Controller\CronController::run', output: null }
