remove_trailing_slash:
    path: /{module}/{url}
    defaults: { _controller: SimpleSAML\Module::removeTrailingSlash }
    requirements:
        url: ".*/$"
    methods: [GET]

add_trailing_slash:
    path: /{url}
    defaults: { _controller: SimpleSAML\Module::addTrailingSlash }
    requirements:
        url: "[a-zA-Z0-9_-]+[^/]$"
    methods: [GET]
