---

frontpage:
  path: /
  defaults:
    _controller: 'SimpleSAML\Controller\FrontpageController::redirect'
  methods: [GET]

frontpage-index:
  path: /index.php
  defaults:
    _controller: 'SimpleSAML\Controller\FrontpageController::redirect'
  methods: [GET]

remove_trailing_slash:
  path: /{module}/{url}
  defaults: {
    _controller: SimpleSAML\Module::removeTrailingSlash
  }
  requirements:
    url: ".*/$"
  methods: [GET]

admin-shortcut:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: admin-main
  methods: [GET]

legacy-route-redirect-admin-index:
  path: /admin/index.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: admin-main
  methods: [GET]
