<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the 
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = array(
	'selectidp' => array (
		'no' => 'Velg din identitetsleverandør',
		'nn' => 'Vel innloggingsteneste',
		'se' => 'Válasszon személyazonosság-szolgáltatót (IdP)',
		'da' => 'Vælg institution (identitetsudbyder)',
		'en' => 'Select your identity provider',
		'de' => 'Wählen sie ihren Identity Provider',
		'sv' => 'Välj din identitetsleverantör',
		'fi' => 'Valitse identiteettillähteeis',
		'es' => 'Seleccione su proveedor de identidad',
		'fr' => 'Séléctionnez votre fournisseur d\'identité',
		'nl' => 'Kies je Identiy Provider',
		'sl' => 'Izberite IdP domače organizacije',
		'hr' => 'Odaberite vašeg davatelja elektroničkih identiteta',
		'hu' => 'Válasszon személyazonosság-szolgáltatót (IdP)',
		'pl' => 'wybierz swojego Dostawcę Tożsamości.',
		'pt' => 'Escolha o seu fornecedor de identidade (IdP)',
		'pt-BR' => 'Selecione seu provedor de identidade',
	),
	'selectidp_full' => array (
		'no' => 'Vennligst velg hvilken identitetsleverandør du vil bruke for å logge inn:',
		'nn' => 'Vel innloggingsteneste (IdP) der du ønskjer å logga inn.',
		'se' => 'Kérjük, válasszon személyazonosság szolgáltatót (IdP), amely Önt azonosítani tudja!',
		'da' => 'Vælg institutionen (identitetsudbyderen) hvor du vil logge ind',
		'en' => 'Please select the identity provider where you want to authenticate:',
		'de' => 'Bitte wählen sie den Identity Provider, bei dem sie sich authentifizieren möchten:',
		'sv' => 'Välj vilken identitetsleverantör du vill logga in med:',
		'fi' => 'Valitse identiteettilähteesi jossa haluat kirjautua',
		'es' => 'Por favor, seleccione el proveedor de identidad donde desea autenticarse',
		'fr' => 'Séléctionnez le fournisseur d\'identité auprès duquel vous souhaitez vous authentifier:',
		'nl' => 'Selecteer de Identity Provider waar je wil authenticeren:',
		'sl' => 'Izberite IdP, na katerem se boste avtenticirali:',
		'hr' => 'Molimo odaberite davatelja elektroničkih identiteta kod kojeg se želite autenticirati:',
		'hu' => 'Kérjük, válassza ki azt a személyazonosság-szolgáltatót (IdP), ahol azonosítani kívánja magát:',
		'pl' => 'Proszę wybrać Dostawcę Tożsamości, przez którego  chcesz się uwierzytelnić:',
		'pt' => 'Por favor, escolha o  fornecedor de identidade (IdP) que irá usar para se autenticar:',
		'pt-BR' => 'Por favor selecione o provedor de identidade ao qual deseja se autenticar',
	),
	'select' => array (
		'no' => 'Velg',
		'nn' => 'Vel',
		'se' => 'Választ',
		'da' => 'Vælg',
		'en' => 'Select',
		'de' => 'Auswahl',
		'sv' => 'Välj',
		'fi' => 'Valitse',
		'es' => 'Seleccione',
		'fr' => 'Séléctionner',
		'nl' => 'Kies',
		'sl' => 'Izberite',
		'hr' => 'Odaberi',
		'hu' => 'Választ',
		'pl' => 'Wybierz',
		'pt' => 'Escolher',
		'pt-BR' => 'Selecione',
	),
	'remember' => array (
		'no' => 'Husk mitt valg',
		'nn' => 'Hugs mitt val',
		'se' => 'Emlékezzen erre',
		'da' => 'Husk valget',
		'en' => 'Remember my choice',
		'de' => 'Meine Auswahl merken',
		'sv' => 'Kom ihåg mitt val',
		'fi' => 'Muista valintani',
		'es' => 'Recordar mi elección',
		'fr' => 'Retenir ce choix',
		'nl' => 'Onthoud mijn keuze',
		'sl' => 'Shrani kot privzeto izbiro',
		'hr' => 'Zapamti moj odabir',
		'hu' => 'Emlékezzen erre',
		'pl' => 'Zapamiętaj mój wybór',
		'pt' => 'Lembrar esta escolha',
		'pt-BR' => 'Lembrar minha escolha',
	),
	'icon_prefered_idp' => array (
		'no' => '[Foretrukket valg]',
		'da' => 'Foretrukket valg',
		'en' => '[Preferred choice]',
		'sv' => 'Prioriterat val',
		'fi' => '[Oletusvalinta]',
		'es' => '[Opción preference]',
		'sl' => 'Preferirana izbira',
		'hu' => '[Kívánt választás]',
		'pl' => 'Preferowany wybór',
	),

);


?>