<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the 
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = array(
	'access_denied' => array (
		'no' => 'Du har ikke tilgang til denne tjenesten',
		'nn' => 'Du har ikkje tilgang til denne tenesta',
		'da' => 'Du har ikke adgang til denne service',
		'en' => 'You do not have access to this service',
		'de' => 'Sie haben keinen Zugriff auf diesen Dienst',
		'sv' => 'Du har inte tillgång till denna tjänst',
		'fi' => 'Sinulla ei ole käyttöoikeutta palveluun',
		'es' => 'No tiene acceso a este servicio.',
		'fr' => 'Vous n\'etes pas autorisé à accéder à ce service',
		'nl' => 'U heeft geen toegang tot deze dienst',
		'sl' => 'Dostop do storitve zavrnjen.',
		'hr' => 'Nemate pristup ovom servisu',
		'hu' => 'Önnek nincs hozzáférése ehhez a szolgáltatáshoz',
		'pl' => 'Dostęp zabroniony',
		'pt' => 'Não tem acesso a este serviço',
		'pt-BR' => 'Você não possui acesso a este serviço',
		'tr' => 'Bu servise giriş izniniz yok.',
	),
	'no_access_to' => array (
		'no' => 'Du har ikke tilgang til følgende tjeneste:',
		'nn' => 'Du har ikkje tilgang til tenesta:',
		'da' => 'Du har ikke adgang til servicen:',
		'en' => 'You do not have access to the service:',
		'de' => 'Sie haben keinen Zugriff auf den Dienst:',
		'sv' => 'Du har inte tillgång till angiven tjänst:',
		'fi' => 'Sinulla ei ole käyttöoikeutta palveluun:',
		'es' => 'No tiene acceso al servicio:',
		'fr' => 'Vous n\'etes pas autorisé à accéder à ce service',
		'nl' => 'U heeft geen toegang tot deze dienst:',
		'sl' => 'Nimate dostopa do te storitve.',
		'hr' => 'Nemate pristup servisu:',
		'hu' => 'Ön nem férhet hozzá ehhez a szolgáltatáshoz:',
		'pl' => 'Nie masz dostępu to tego serwisu:',
		'pt' => 'Não tem acesso ao serviço:',
		'pt-BR' => 'Você não possui acesso a este serviço',
		'tr' => 'Bu servise giriş izniniz yok.',
	),
	'contact_home' => array (
		'no' => 'Hvilke tjenester du har tilgang til er bestemt av din vertsorganisasjon. Ta kontakt med din lokale brukerstøtte for spørsmål.',
		'nn' => 'Tilgang til tenester er kontroller av utdanningsorganisasjonen din.  Ta kontakt med din lokale IT-avdeling for meir informasjon',
		'da' => 'Adgang til services bestemmes af din hjemmeorganisation. Kontakt venligst din lokale helpdesk for spørgsmål.',
		'en' => 'Access to services is controlled by your home organization. Please contact your local it support for questions.',
		'de' => 'Der Zugriff auf Dienste wird von Ihrer Heimatorganisation geregelt. Bitte wenden Sie sich mit Fragen an Ihre lokale IT Unterstützung.',
		'sv' => 'Tillgång till tjänster kontrolleras av din hemmaorganisation. Ta kontakt med din lokala support om du har några frågor.',
		'fi' => 'Käyttöoikeuksista palveluun vastaa kotiorganisaatiosi. Ota yhteys paikalliseen tukeen lisätietoja varten.',
		'es' => 'El acceso al servicio se controla por su organización. Por favor, para cualquier consulta contacte con el personal de su organización.',
		'fr' => 'L\'accès à ce service est restreint par votre institution. Contactez votre support technique pour avoir plus d\'informations',
		'nl' => 'Toegang tot diensten wordt verleend door uw organisatie. Neem contact op met uw ICT afdeling.',
		'sl' => 'Možnost dostopa do storitve ureja vaša domača organizacija. Obrnite se na njihov oddelek za pomoč uporabnikom.',
		'hr' => 'Pristup ovom servisu kontrolira vaš davatelj elektroničkih identiteta. Za dodatne informacije molimo kontaktirajte vašeg davatelja elektroničkih identiteta.',
		'hu' => 'A hozzáférését ehhez a szolgáltatáshoz az ön szervezete szabályozza. Vegye fel a kapcsolatot a helyi IT felelőssel!',
		'pl' => 'Dostęp do serwisu jest kontrolowany przez Twoją organizację macierzystą. W sprawie pytań prosze skontaktować się z pomocą techniczną w Twojej organizacji.',
		'pt' => 'O acesso a serviços é controlado pela sua organização de origem. Para obter ajuda, contacte o serviço de apoio ao utilizador da sua organização.',
		'pt-BR' => 'O acesso a estes serviços é controlado pela sua organização principal. Entre em contato com a equipe local de suporte para ajudá-lo.',
		'tr' => 'Servislere erişim organizasyonunuz tarafından kontrol edilmektedir. Lütfen sorularınız için yerel ilgilerle iletişime geçiniz.',
	),

);


?>