<?php
/**
 * Maps Microsoft .NET Framework ClaimTypes to Names
 * Names in this version are used as described by Microsoft.
 * @see https://msdn.microsoft.com/en-us/library/hh159803.aspx
 */
$attributemap = array(
    'http://schemas.xmlsoap.org/ws/2009/09/identity/claims/actor' => 'Actor',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/anonymous' => 'Anonymous',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/authenticated' => 'Authentication',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationinstant' => 'AuthenticationInstant',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod' => 'AuthenticationMethod',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/authorizationdecision' => 'AuthorizationDecision',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/cookiepath' => 'CookiePath',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/country' => 'Country',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dateofbirth' => 'DateOfBirth',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarygroupsid' => 'DenyOnlyPrimaryGroupSid',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarysid' => 'DenyOnlyPrimarySid',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/denyonlysid' => 'DenyOnlySid',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlywindowsdevicegroup' => 'DenyOnlyWindowsDeviceGroup',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/dns' => 'Dns',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/dsa' => 'Dsa',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/email' => 'Email',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/expiration' => 'Expiration',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/expired' => 'Expired',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/gender' => 'Gender',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname' => 'GivenName',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid' => 'GroupSid',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/hash' => 'Hash',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/homephone' => 'HomePhone',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/ispersistent' => 'IsPersistent',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/locality' => 'Locality',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/mobilephone' => 'MobilePhone',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name' => 'Name',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier' => 'NameIdentifier',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/otherphone' => 'OtherPhone',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/postalcode' => 'PostalCode',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/primarygroupsid' => 'PrimaryGroupSid',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/primarysid' => 'PrimarySid',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/role' => 'Role',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/rsa' => 'Rsa',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/serialnumber' => 'SerialNumber',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/sid' => 'Sid',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/spn' => 'Spn',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/stateorprovince' => 'StateOrProvince',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/streetaddress' => 'StreetAddress',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname' => 'Surname',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/system' => 'System',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/thumbprint' => 'Thumbprint',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn' => 'Upn',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/uri' => 'Uri',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/userdata' => 'UserData',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/version' => 'Version',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/webpage' => 'Webpage',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname' => 'WindowsAccountName',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsdeviceclaim' => 'WindowsDeviceClaim',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsdevicegroup' => 'WindowsDeviceGroup',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsfqbnversion' => 'WindowsFqbnVersion',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority' => 'WindowsSubAuthority',
    'http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsuserclaim' => 'WindowsUserClaim',
    'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/x500distinguishedname' => 'X500DistinguishedName',
); 
