<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the 
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = array(
	'warning' => array (
		'no' => 'Du har nå kommet til et test-oppsett. Dette oppsettet for autentisering er kun til bruk for testing og pre-produksjon verifikasjon. Hvis noen sendte deg en link som pekte hit, og du ikke er <i>en tester</i> så fikk du nok en feil link, og <b>skulle ikke vært her</b>.',
		'nn' => 'Du er no inne på eit testsystem.  Denne autentiseringsløysinga er for testing og beta-drift, ikkje for vanleg drift.  Dersom du har fått peikar hit og du ikkje er  <i>utviklar</i>, så er du truleg på feil plass og <i>skulle ikkje vore her</i>.',
		'da' => 'Du tilgår nu et pre-produktions-system. Dette autentificeringssetup er kun til test og pre-produktion verifikation. Hvis nogen har sendt et link, som peger her og du ikke er en <i>tester</i>, så har du sikekrt fået et forkert lin og burde <b>ikke være her.</b> ',
		'en' => 'You are now accessing a pre-production system. This authentication setup is for testing and pre-production verification only. If someone sent you a link that pointed you here, and you are not <i>a tester</i> you probably got the wrong link, and should <b>not be here</b>.',
		'sv' => 'Du har kommit till en tjänst som ännu inte är i drift. Denna autentisieringskonfiguration är för testning och tidig produktionskontroll. Om någon har skickat dig en länk hit och du inte är en <i>en testare</i> har du troligtvis fått fel länk.',
		'fi' => 'Olet siirtymässä testijärjestelmään. Käyttäjätunnistus on tarkoitettu vain testaukseen. Jos sait linkin järjestelmään ja et ole <i>testikäyttäjä</i>, sait todennäköisesti väärän linkin ja sinun ei pitäisi <b>olla täällä</b>.',
		'es' => 'Está accediendo a un sistema en pre-producción. Esta configuración es únicamente para pruebas y para verificación del sistema de preproducción. Si siguió un enlace que alguien le envió para llegar hasta aquí y no es un <i>probador</i> probablemente se trata de un error, y usted <b>no debería estar aquí</b>',
		'nl' => 'Je gaat nu een pre-productiesysteem gebruiken. Deze authenticatie is uitsluitend opgezet voor testen en pre-productie-verfificatie. Als iemand je een link hierheen stuurde, en je bent geen <i>tester</i>, dan is dit waarschijlijk een vergissing en zou je <b>niet hier moeten zijn</b>.',
		'sl' => 'Dostopate do predprodukcijskega sistema, ki je namenjen izključno preizkušanju. V primeru da ste pristali na tej strani med postopkom prijave v produkcijsko storitev, je storitev verjetno napačno nastavljena.',
		'hr' => 'Pristupate sustavu koji se nalazi u predprodukcijskoj fazi. Ove autentikacijske postavke služe za testiranje i provjeru ispravnosti rada predprodukcijskog sustava. Ako vam je netko poslao adresu koja pokazuje na ovu stranicu, a vi niste osoba zadužena za <i>testiranje</i>, vjerojatno ste <b>na ovu stranicu došli greškom</b>.',
		'pl' => 'Korzystasz w tej chwili z wersji testowej systemu. To ustawienie uwierzytelniania jest tylko dla testów. Jeśli ktoś wysłał Ci link kierujący tutaj, a ty nie jesteś <i>testerem</i> to prawdopodobnie otrzymałeś błędny link i <b>nie powinieneś być tutaj</b>.',
		'pt' => 'Está a aceder a um sistema em pré-produção. Este passo de autenticação servirá apenas para testes e verificações de pré-produção. Se alguém lhe enviou este endereço, e você não é um <i>testador</i>, então provavelmente recebeu um link errado, e <b>não deveria estar aqui</b>.',
		'tr' => 'Şu anda tamamlanmamış bir sisteme giriyorsunuz. Bu doğrulama kurulumu sadece test ve tamamlanma öncesi onaylama amaçlıdır. Eğer birileri size burayı gösteren bir bağlantı gönderdiyse, ve siz <i>test edici</i> değilseniz, muhtemelen yanlış bir bağlantı aldınızı, ve şu anda <b>burada olmamalısınız</b>. ',
	),
	'warning_header' => array (
		'no' => 'Advarsel om at dette er et test oppsett',
		'nn' => 'Varsel om tilgang til test-system',
		'da' => 'Advarsel om adgang til et pre-produktions-system.',
		'en' => 'Warning about accessing a pre-production system',
		'sv' => 'Varning om åtkomst till testsystem',
		'fi' => 'Varoitus testijärjestelmää siirtymisestä',
		'es' => 'Aviso sobre el acceso a un sistema en pre-producción',
		'nl' => 'Waarschuwing: dit is een pre-productiesysteem',
		'sl' => 'Opozorilo o dostopu do predprodukcijskega sistema',
		'hr' => 'Upozorenje o pristupanju predprodukcijksom sustavu',
		'pl' => 'Uwaga, korzystasz z wersji testowej systemu',
		'pt' => 'Aviso ao aceder a sistema em pré-produção',
		'tr' => 'Tamamlanmamış bir sisteme erişim hakkında uyarı',
	),
	'yes' => array (
		'no' => 'Ja, jeg holder på å teste innlogging, og vet dette er et test-system.',
		'nn' => 'Ja, eg veit at eg no går inn i ei løysing som ikkje er i drift, men i test',
		'da' => 'Ja, jeg ved jeg er ved at tilgå et pre-produktions-system.',
		'en' => 'Yes, I know I am accessing a pre-production system',
		'sv' => 'Ja, jag vet att jag försöker använda ett testsystem',
		'fi' => 'Hyväksyn siirtyväni testijärjestelmään',
		'es' => 'Sí, sé que estoy accediendo a un sistema en pre-producción',
		'nl' => 'Ja, ik begrijp dat ik een pre-productiesysteem ga gebruiken',
		'sl' => 'Da, zavedam se, da dostopam do predprodukcijskega okolja',
		'hr' => 'Da, znam da pristupam sustavu koji je u predprodukcijskoj fazi',
		'pl' => 'Tak, wiem, że korzystam z wersji testowej.',
		'pt' => 'Sim, eu sei que estou a aceder a um sistema em pré-produção',
		'tr' => 'Evet, tamanlanmamış bir sisteme girdiğimin farkındayım.',
	),

);


?>