saml-proxy-invalidSession:
    path:       /proxy/invalidSession
    defaults:   { _controller: 'SimpleSAML\Module\saml\Controller\Proxy::invalidSession' }
saml-disco:
    path:       /disco
    defaults:   { _controller: 'SimpleSAML\Module\saml\Controller\Disco::disco' }
saml-sp-discoResponse:
    path:       /sp/discoResponse
    defaults:   { _controller: 'SimpleSAML\Module\saml\Controller\ServiceProvider::discoResponse' }
saml-sp-wrongAuthnContextClassRef:
    path:       /sp/wrongAuthnContextClassRef
    defaults:   { _controller: 'SimpleSAML\Module\saml\Controller\ServiceProvider::wrongAuthnContextClassRef' }
saml-sp-assertionConsumerService:
    path:       /sp/assertionConsumerService/{sourceId}
    defaults:   { _controller: 'SimpleSAML\Module\saml\Controller\ServiceProvider::assertionConsumerService' }
saml-sp-singleLogoutService:
    path:       /sp/singleLogoutService/{sourceId}
    defaults:   { _controller: 'SimpleSAML\Module\saml\Controller\ServiceProvider::singleLogoutService' }
saml-sp-metadata:
    path:       /sp/metadata/{sourceId}
    defaults:   { _controller: 'SimpleSAML\Module\saml\Controller\ServiceProvider::metadata' }
