language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm
    - nightly

install: travis_retry composer update --no-interaction --no-progress --no-suggest --prefer-stable
