<?php

/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * If you want to contribute to translation, you must instead use the 
 * SimpleSAMLphp translation portal:
 * https://translation.rnd.feide.no/index.php?aid=simplesamlphp
 *
 * This file is automatically generated from the translation portal.
 */

$lang = array(
	'title_no_user' => array (
		'no' => 'OpenID tilbyder',
		'en' => 'OpenID provider',
	),
	'title_user' => array (
		'no' => 'OpenID for %USERID%',
		'en' => 'OpenID for %USERID%',
	),
	'user_page_for' => array (
		'no' => 'Dette er OpenID brukersiden for <code>%USERID%</code>.',
		'en' => 'This is the OpenID user page for <code>%USERID%</code>.',
	),
	'view_own_page' => array (
		'no' => 'Se på din egen OpenID side.',
		'en' => 'View your own OpenID page.',
	),
	'login_view_own_page' => array (
		'no' => 'Logg på for å se på din egen OpenID side.',
		'en' => 'Log in to view your own OpenID page.',
	),
	'your_identifier' => array (
		'en' => 'To log in with your OpenID identifier, use the following identifier:',
	),
	'howto_delegate' => array (
		'en' => 'You can also delegate a different identifier to use this OpenID provider. To do that, you need to add the following to the <code>&lt;head&gt;</code>-element on the webpage of that identifier:',
	),
	'logout_title' => array (
		'no' => 'Logg av',
		'en' => 'Log out',
	),
	'logout' => array (
		'no' => 'Trykk her for å logge ut av din OpenID bruker.',
		'en' => 'Click here to log out of your OpenID user.',
	),
	'confirm_question' => array (
		'no' => 'Ønsker du å logge på %SITEURL%?',
		'en' => 'Do you wish to log on to %SITEURL%?',
	),
	'remember' => array (
		'no' => 'Husk dette valget',
		'nn' => 'Hugs denne avgjerda',
		'da' => 'Husk dette',
		'en' => 'Remember this decision',
		'de' => 'Diese Entscheidung merken',
		'sv' => 'Spara detta beslut',
		'es' => 'Recordar esta decisión',
		'nl' => 'Onthoud deze keuze',
		'sl' => 'Zapomni si to odločitev',
		'hr' => 'Zapamti ovu odluku',
		'hu' => 'Emlékezzen erre a választásra',
		'pl' => 'Zapamiętaj tą decyzję',
		'pt' => 'Lembrar esta decisão',
		'pt-BR' => 'Lembrar desta decisão',
		'tr' => 'Kararımı hatırla',
	),
	'confirm' => array (
		'no' => 'Bekreft',
		'nn' => 'Stadfest',
		'da' => 'Bekræft',
		'en' => 'Confirm',
		'de' => 'Bestätigen',
		'sv' => 'Bekräfta',
		'es' => 'Confirmar',
		'nl' => 'Bevestig',
		'sl' => 'Potrdi',
		'hr' => 'Potvrdi',
		'hu' => 'Megerősít',
		'pl' => 'Potwierdź',
		'pt' => 'Confirmar',
		'pt-BR' => 'Confirmar',
		'tr' => 'Doğrula',
	),
	'notconfirm' => array (
		'no' => 'Ikke bekreft',
		'nn' => 'Treng ikkje stadfesting',
		'da' => 'Bekræft ikke',
		'en' => 'Do not confirm',
		'de' => 'Nicht Bestätigen',
		'sv' => 'Bekräfta inte',
		'es' => 'No confirmar',
		'nl' => 'Weiger',
		'sl' => 'Ne potrdi',
		'hr' => 'Nemoj potvrditi',
		'hu' => 'Nem erősíti meg',
		'pl' => 'Nie potwierdzaj',
		'pt' => 'Não confirmar',
		'pt-BR' => 'Não confirmar',
		'tr' => 'Doğrulama',
	),
	'trustlist_trustedsites' => array (
		'no' => 'Klarerte websider',
		'nn' => 'Tiltrudde partnarar',
		'da' => 'Hjemmesider du har tillid til',
		'en' => 'Trusted Sites',
		'de' => 'Vertraute Seiten',
		'sv' => 'Godkända sajter',
		'es' => 'Sitios de confianza',
		'nl' => 'Trusted Sites',
		'sl' => 'Zaupanja vredne strani',
		'hr' => 'Sjedišta kojima vjerujete',
		'hu' => 'Megbízható oldalak',
		'pl' => 'Zaufane strony',
		'pt' => 'Sites confiáveis',
		'pt-BR' => 'Sites Confiáveis',
		'tr' => 'Güvenilir Siteler',
	),
	'trustlist_remove' => array (
		'no' => 'Fjern',
		'nn' => 'Ta vekk',
		'da' => 'Fjern',
		'en' => 'Remove',
		'de' => 'Ausgewählte löschen',
		'sv' => 'Ta bort',
	),
	'trustlist_nosites' => array (
		'no' => 'Ingen sites er husket. Når du autentiserer deg hos en site, kan du velge å legge den til denne listen ved å velge <q>Husk dette valget</q>.',
		'nn' => 'Ingen tenester er lagra.  Når du logger inn på ei teneste, kan du velja å leggja ho inn på lista over tiltrudde partnarar ved å velja <q>Hugs denne avgjerda</q>.',
		'da' => 'Der er ikke gemt nogle sites. Når authenticater mod et site kan du vælge at gemme sitet i denne liste ved at vælge <q>Gem mit valg</q>',
		'en' => 'No sites are trusted. When you authenticate with a site, you can choose to add it to this list by choosing <q>Remember this decision</q>.',
		'sv' => 'Inga sajter är sparade. När du loggar in på en sajt kan du välja om du ska lägga den i listan genom att välja <q>Spara detta beslut</q>.',
	),

);


?>